# obstacle_range: 1
# raytrace_range: 1

# footprint: [[-0.3,-0.16],[-0.3,0.16], [0.3, 0.16], [0.3,-0.16]]
# #robot_radius: ir_of_robot

# inflation_radius: 0.5
# cost_scaling_factor: 2
# # map_type: costmap

# observation_sources: scan
# scan: {sensor_frame: lidar_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}

footprint: [[-0.3,-0.16],[-0.3,0.16], [0.3, 0.16], [0.3,-0.16]]
always_send_full_costmap: true

obstacle_layer:
 enabled: true
 obstacle_range: 3.0
 raytrace_range: 4.0
 inflation_radius: 0.2
 track_unknown_space: true
 combination_method: 1
 observation_sources: scan
 scan: {sensor_frame: lidar_link,  observation_persistence: 0.0, max_obstacle_height: 0.4, min_obstacle_height: 0.0, data_type: LaserScan, topic: scan, marking: true, clearing: true}

inflation_layer:
  enabled:              true
  cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.5  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  map_topic:            "/map"
