local_costmap:
  global_frame: map
  robot_base_frame: base_footprint

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5

  static_map: false  
  rolling_window: true
  width: 4
  height: 4
  resolution: 0.05
  static_layer:
        - {name: static_layer, type: "costmap_2d::StaticLayer"}
        - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
        - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  static_layer:
        enabled: true
        map_topic: "map"
  inflation_layer:
        enabled: true
        cost_scaling_factor: 0.55
        inflation_radius: 0.2
  
      